// @krishalaya/tokens · GENERATED from designer_pack/tokens/design-tokens.json — DO NOT HAND-EDIT.
// Regenerate: node sync-from-design-system.js (source generated by hand1_tokens_export.py,
// which itself parses system/tokens.css + system/web/web-tokens.css — the true canon).
// Batch HAND-1, 2026-07-22. Supersedes the pre-HAND-1 placeholder palette/font-stack,
// which did not correspond to canon at all (zero consumers existed at time of correction,
// grep-verified against krishalaya/ — see hand1_report.md).
// Bridges `web.dark` (40 dark-console tokens, generated by hand1_tokens_export.py from
// system/web/web-tokens.css's [data-theme="dark"] block, APPLY-7/G0-2-Q40) — previously present in
// design-tokens.json but never bridged into this package (packages/ui's own internal/theme.ts had
// disclosed this as a GENUINE GAP / ENGINEERING-OWED item at DEV-15/17). DEV-19 closes it.
export const darkColors = {
  primary: {
    '50': "#1c3527",
    '100': "#234631",
  },
  earth: {
    '50': "#161d24",
    '100': "#202832",
    '200': "#2a3440",
    '300': "#3a4652",
  },
  ink: {
    '400': "#8a95a0",
    '500': "#aab4bd",
    '600': "#c3cad1",
    '700': "#e8ebee",
  },
  // light-tint remap only (no -base/-dark change needed for these 5 semantics in dark scope)
  success: {
    light: "#12301e",
  },
  warning: {
    light: "#3a2a12",
  },
  danger: {
    light: "#3a1713",
  },
  info: {
    light: "#12293a",
  },
  ai: {
    light: "#2a1836",
  },
  // AA-corrected dark-only TEXT roles (APPLY-7 apply7_aa_report.json — 3 of BRAND-025's own named
  // AA failures + 2 more this program's own wider census found; see web-tokens.css lines 178-202)
  textDark: {
    primaryAvatarDark: "#7fc28e",
    success: "#6fcf97",
    warning: "#f0b055",
    danger: "#e57373",
    info: "#6bb0e8",
    ai: "#b67fcc",
  },
  surface: {
    page: "#12171d",
    card: "#1b232b",
    'card-warm': "#202832",
    overlay: "rgba(0,0,0,0.6)",
  },
  border: {
    subtle: "#29323c",
    default: "#33404b",
    strong: "#4a5a67",
  },
  table: {
    'header-bg': "#202832",
    'row-hover': "#222c36",
    'row-selected': "#1c3527",
  },
  chartGrid: "#29323c",
} as const;
export type DarkColorScale = typeof darkColors;
