// apps/admin-api/src/core/media/admin-object-store.ts · the S3 read boundary for the ADMIN realm
// (PC-56 ADMIN-1c, closes ADMIN-1-Q2).
//
// WHY THIS IS DOWNLOAD-ONLY. apps/api's ObjectStore can presign PUTs, upload generated bytes and fetch objects
// server-side, because it is the service that CREATES media. admin-api creates none: a platform operator needs to
// hand somebody an artefact that already exists (the PDF of a SaaS invoice). So this class exposes exactly one verb.
// There is no upload path and no write credential wired into this realm, which keeps the blast radius of a stolen
// admin token at "can read a document it was already allowed to read".
//
// THE SIGNER IS SHARED, NOT COPIED. `presignS3Url` comes from `@krishalaya/storage` — the package this wave created
// precisely so that URL-signing exists once in the monorepo. Copying it here was the cheap path and would have left
// two implementations to keep in step; a signing bug fixed in one and not the other is the kind of defect that is
// invisible until someone's link stops working (or, worse, works longer than it should).
//
// FAILS CLOSED. With no bucket configured this throws rather than returning a URL that cannot work: a misconfigured
// deploy must not hand an operator a broken link and let them conclude the document is missing.
import { Injectable } from '@nestjs/common';
import { presignS3Url } from '@krishalaya/storage';
import { AdminConfig } from '../config/admin-config';
import { MediaNotConfiguredError } from './media.errors';

@Injectable()
export class AdminObjectStore {
  constructor(private readonly config: AdminConfig) {}

  /** True when this deploy can actually serve a download. Callers use it to say "not available here" instead of
   *  throwing at a page render — a console that 500s because storage is unconfigured is less useful than one that
   *  says so. */
  get configured(): boolean {
    const e = this.config.env;
    return !!(e.MEDIA_BUCKET && e.MEDIA_ACCESS_KEY_ID && e.MEDIA_SECRET_ACCESS_KEY);
  }

  /**
   * A time-limited GET URL for one object key.
   *
   * The expiry defaults to the configured window (120s) and is deliberately short: this is a link to a tax document,
   * and a link that outlives the click is a link that gets pasted into a chat thread and forwarded. The caller may
   * shorten it further but never lengthen it beyond the configured maximum — an "expires in a week" download is a
   * permanent public URL with extra steps.
   */
  presignDownload(key: string, expiresSec?: number): string {
    const e = this.config.env;
    if (!this.configured) throw new MediaNotConfiguredError();
    const max = e.MEDIA_PRESIGN_EXPIRY_SEC;
    const expires = expiresSec === undefined ? max : Math.max(1, Math.min(expiresSec, max));
    return presignS3Url({
      method: 'GET',
      region: e.MEDIA_REGION,
      bucket: e.MEDIA_BUCKET,
      key,
      accessKeyId: e.MEDIA_ACCESS_KEY_ID,
      secretAccessKey: e.MEDIA_SECRET_ACCESS_KEY,
      endpoint: e.MEDIA_ENDPOINT,
      forcePathStyle: e.MEDIA_FORCE_PATH_STYLE,
      expiresSec: expires,
    });
  }

  get expirySec(): number { return this.config.env.MEDIA_PRESIGN_EXPIRY_SEC; }
}
