// modules/dairy/__tests__/tenant6c5-standing-instruction.spec.ts · PC-56 TENANT-6c-5 · the half W169 contrasts against.
//
// *"Deductions above 25% of gross need the member's fresh consent, **not just standing instructions**."*
//
// TENANT-6c-4 built the fresh consent and the destinations, and said out loud what it had not built: *"Nothing
// ASSEMBLES the lines yet. The cycle's generation pass passes `deductions: []`, so a cadence-built bill still carries
// none, and W169's ₹1,84,300 this cycle is still zero on the automatic path."* This wave is the standing instruction
// that makes assembly AUTHORISED rather than merely automatic, the cap that keeps the automatic path below the line
// where a human must ask, and the reader for `loan_products.repayment_style = 'milk_bill_deduction'` — a value that
// has existed since the fintech module was written and that nothing had ever selected on.
import { Logger } from '@nestjs/common';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { assemblyCapMinor, DeductionCandidate, planDeductions } from '../domain/deduction-plan';
import { DairyDeductionInstruction } from '../domain/dairy-deduction-instruction.entity';
import { DairyDeductionInstructionRepository } from '../repositories/dairy-deduction-instruction.repository';
import { DairyDeductionAssemblerService } from '../services/dairy-deduction-assembler.service';
import { DairyMemberCredit } from '../domain/dairy-member-credit.entity';
import { DairyBillCycleService } from '../services/dairy-bill-cycle.service';
import { DeductionInstructionInvalidError } from '../domain/dairy.errors';
import { LoanRepository } from '../../fintech/repositories/loan.repository';
import { Loan } from '../../fintech/domain/loan.entity';

const MIGRATION = '../../../../../../db/migrations/0161_dairy_deduction_instructions.sql';
const SEED_NOTIFS = '../../../../../../db/seeds/core/0007_notification_events_templates.sql';
const read = (rel: string) => fs.readFileSync(path.join(__dirname, rel), 'utf8');
const metrics = { inc: jest.fn(), observe: jest.fn(), timing: jest.fn() };
const NOW = new Date('2026-07-16T04:00:00.000Z');

const candidate = (over: Partial<DeductionCandidate> = {}): DeductionCandidate => ({
  typeId: over.typeId ?? 'lv-feed', typeCode: over.typeCode ?? 'feed_credit',
  sourceType: over.sourceType ?? 'dairy_member_credit', sourceId: over.sourceId ?? 'credit1',
  outstandingMinor: over.outstandingMinor ?? 50_000n, maxPerCycleMinor: over.maxPerCycleMinor ?? null,
  since: over.since ?? '2026-07-01', id: over.id ?? 'credit1',
});

/* ----------------------------------------------------------------------------------------------------------- */
describe('THE CAP — the automatic path may never need a human to ask', () => {
  it('is the LOWER of the assembly cap and the consent threshold', () => {
    // This is what makes W169's sentence true rather than aspirational: standing instructions govern below the line,
    // fresh consent above it. If the assembler could cross the line it would produce 312 bills that all need a
    // member's answer before payday — a queue of 312 conversations, generated by software, on a Thursday.
    expect(assemblyCapMinor(400_000n, 25, 25)).toBe(100_000n);
    expect(assemblyCapMinor(400_000n, 40, 25)).toBe(100_000n);   // a loose assembly cap cannot outrun consent
    expect(assemblyCapMinor(400_000n, 10, 25)).toBe(40_000n);    // a kinder cooperative caps itself lower
  });

  it('is zero when either setting is zero, and on a bill worth nothing', () => {
    expect(assemblyCapMinor(400_000n, 0, 25)).toBe(0n);          // assembly switched off by setting
    expect(assemblyCapMinor(400_000n, 25, 0)).toBe(0n);
    expect(assemblyCapMinor(0n, 25, 25)).toBe(0n);
  });

  it('truncates in the MEMBER\'s favour and never touches a float', () => {
    // 33% of 1,001 is 330.33 minor units; the third of a paisa stays with the family.
    expect(assemblyCapMinor(1_001n, 33, 100)).toBe(330n);
    const code = read('../domain/deduction-plan.ts')
      .replace(/\/\*[\s\S]*?\*\//g, '').split('\n').filter((l) => !l.trim().startsWith('//')).join('\n');
    expect(code).not.toMatch(/Number\(|parseFloat|\d\.\d/);
  });

  it('reads BOTH settings and refuses to guess either', async () => {
    const tx = { query: jest.fn().mockResolvedValue({ rows: [{ key: 'dairy.deduction_assembly_max_pct', pct: 25 }] }) };
    const repo = new DairyDeductionInstructionRepository({ forTenant: () => ({ query: jest.fn() }) } as never);
    // Only one of the two came back — a database whose seed did not run. Inventing 100 would let software take a
    // whole fortnight's milk without asking anybody, which is worse than a readable failure (0158's ruling).
    await expect(repo.assemblyPct(tx as never, 'tA')).rejects.toThrow(/dairy\.deduction_consent_pct is missing/);
    // The tenant's OWN override, then the platform default — a join on `ts.tenant_id = $1`. Joining on anything else
    // (the mutation run tried `IS NULL`) would silently ignore a cooperative that had tightened its own cap.
    expect(tx.query.mock.calls[0][0]).toMatch(/COALESCE\(ts\.value, d\.default_value\)/);
    expect(tx.query.mock.calls[0][0]).toMatch(/LEFT JOIN tenant_settings ts ON ts\.key = d\.key AND ts\.tenant_id = \$1/);
  });
});

/* ----------------------------------------------------------------------------------------------------------- */
describe('THE PLAN — oldest debt first, and nothing hidden', () => {
  it('takes the whole outstanding when the cap can carry it', () => {
    const plan = planDeductions(400_000n, 100_000n, [candidate({ outstandingMinor: 50_000n })]);
    expect(plan.lines).toEqual([expect.objectContaining({ sourceId: 'credit1', amountMinor: 50_000n })]);
    expect(plan.totalMinor).toBe(50_000n);
    expect(plan.deferred).toEqual([]);
  });

  it('honours the member\'s INSTALMENT over the debt', () => {
    // The humane case, and the one thing no other table can express: "₹200 a fortnight, not the whole ₹500 at once".
    const plan = planDeductions(400_000n, 100_000n, [candidate({ outstandingMinor: 50_000n, maxPerCycleMinor: 20_000n })]);
    expect(plan.totalMinor).toBe(20_000n);
    expect(plan.deferred).toEqual([]);   // taking the agreed instalment is not a deferral
  });

  it('recovers the OLDEST debt first, across types, and never by size or by whose debt it is', () => {
    // Recovering a bank's loan before the cooperative's own feed shop — or the reverse — is a policy W169 does not
    // state, and choosing one silently would decide whose debt a family pays first. Oldest-first is the one order
    // that needs no justification; 0161's header names the per-type priority it does not build.
    // THE OLDER DEBT IS THE SMALLER ONE, deliberately: the first version of this fixture made the oldest debt also
    // the largest, so "largest first" produced the same answer and a mutation run walked straight through it.
    const plan = planDeductions(400_000n, 60_000n, [
      candidate({ id: 'loan1', sourceId: 'loan1', sourceType: 'loan', typeId: 'lv-loan', typeCode: 'loan_emi', outstandingMinor: 40_000n, since: '2026-04-01' }),
      candidate({ id: 'credit1', sourceId: 'credit1', outstandingMinor: 500_000n, since: '2026-07-01' }),
    ]);
    expect(plan.lines).toEqual([
      expect.objectContaining({ sourceId: 'loan1', amountMinor: 40_000n }),      // oldest, in full
      expect.objectContaining({ sourceId: 'credit1', amountMinor: 20_000n }),    // then whatever the cap has left
    ]);
    expect(plan.deferred).toEqual([
      { sourceType: 'dairy_member_credit', sourceId: 'credit1', wantedMinor: 500_000n, takenMinor: 20_000n },
    ]);
  });

  it('breaks a same-day tie on the id, so two runs of the same fortnight agree', () => {
    const plan = planDeductions(400_000n, 30_000n, [
      candidate({ id: 'b', sourceId: 'b', outstandingMinor: 30_000n, since: '2026-07-01' }),
      candidate({ id: 'a', sourceId: 'a', outstandingMinor: 30_000n, since: '2026-07-01' }),
    ]);
    expect(plan.lines[0].sourceId).toBe('a');
  });

  it('takes a debt PARTLY rather than skipping it — and reports what it could not take', () => {
    // A family with one big debt would otherwise have nothing recovered for ever and the cooperative's books would
    // never move. What must not happen is the partial take being invisible.
    const plan = planDeductions(400_000n, 40_000n, [candidate({ outstandingMinor: 500_000n })]);
    expect(plan.totalMinor).toBe(40_000n);
    expect(plan.deferred).toEqual([{ sourceType: 'dairy_member_credit', sourceId: 'credit1', wantedMinor: 500_000n, takenMinor: 40_000n }]);
  });

  it('never exceeds its cap, however many arrangements there are', () => {
    const many = Array.from({ length: 20 }, (_, i) => candidate({ id: `c${i}`, sourceId: `c${i}`, outstandingMinor: 30_000n, since: `2026-07-${String(i + 1).padStart(2, '0')}` }));
    const plan = planDeductions(400_000n, 100_000n, many);
    expect(plan.totalMinor).toBe(100_000n);
    expect(plan.lines.reduce((a, l) => a + l.amountMinor, 0n)).toBe(100_000n);
    expect(plan.lines.length).toBe(4);   // three whole and one part
  });

  it('REFUSES a cap bigger than the gross rather than trusting its caller', () => {
    // The invariant the file exists for. A caller that computed the cap wrongly (or read the wrong setting) would
    // otherwise build 312 bills whose deductions exceed their gross, and the aggregate would refuse them one at a
    // time on payday. Better to stop here, loudly.
    expect(() => planDeductions(100n, 1_000n, [candidate({ outstandingMinor: 500n })])).toThrow(/overran its cap/);
  });

  it('applies the cap to the TOTAL, not to each line', () => {
    // `remaining -= take` is what makes the cap a budget rather than a per-line limit; without it three ₹400 debts
    // would take ₹1,200 against a ₹500 cap.
    const plan = planDeductions(400_000n, 50_000n, [
      candidate({ id: 'a', sourceId: 'a', outstandingMinor: 40_000n, since: '2026-07-01' }),
      candidate({ id: 'b', sourceId: 'b', outstandingMinor: 40_000n, since: '2026-07-02' }),
    ]);
    expect(plan.totalMinor).toBe(50_000n);
    expect(plan.lines.map((l) => l.amountMinor)).toEqual([40_000n, 10_000n]);
  });

  it('takes nothing at all when the cap is zero, and skips a settled debt', () => {
    expect(planDeductions(400_000n, 0n, [candidate()]).lines).toEqual([]);
    expect(planDeductions(400_000n, 100_000n, [candidate({ outstandingMinor: 0n })]).lines).toEqual([]);
  });
});

/* ----------------------------------------------------------------------------------------------------------- */
describe('THE ARRANGEMENT — what the member agreed to', () => {
  const base = {
    id: 'i1', tenantId: 'tA', membershipId: 'mem1', typeId: 'lv-feed', typeCode: 'feed_credit',
    sourceId: null, maxPerCycleMinor: null, authorisedBy: 'farmer1', authorisedAt: NOW,
    channel: 'app' as const, assistedBy: null, recordedBy: 'farmer1', note: null,
  };

  it('publishes the MEMBER as the recipient — an arrangement recorded silently is software helping itself', () => {
    const i = DairyDeductionInstruction.authorise({ ...base, maxPerCycleMinor: 20_000n , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } });
    const [e] = i.pullEvents();
    expect(e.type).toBe('dairy.deduction_instruction_authorised');
    expect(e.payload).toMatchObject({ userId: 'farmer1', typeCode: 'feed_credit', maxPerCycleMinor: '20000' });
  });

  it('an AMBASSADOR may sit with the member — and only that channel may name one', () => {
    // 0003's own consent-channel vocabulary, third wave running: a farmer with no smartphone arranges this beside an
    // ambassador or over an IVR call, and a platform that only accepts `app` has excluded the people it exists for.
    expect(DairyDeductionInstruction.authorise({ ...base, channel: 'ambassador_assisted', assistedBy: 'amb1' , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } }).isActive).toBe(true);
    expect(() => DairyDeductionInstruction.authorise({ ...base, channel: 'ambassador_assisted' , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } })).toThrow(DeductionInstructionInvalidError);
    expect(() => DairyDeductionInstruction.authorise({ ...base, channel: 'ivr', assistedBy: 'amb1' , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } })).toThrow(DeductionInstructionInvalidError);
  });

  it('refuses an instalment of ZERO — that is a revocation wearing an instalment\'s clothes', () => {
    // It would otherwise sit in the table looking active while the assembler skipped it for ever: a member believing
    // their feed credit is being paid off, and a cooperative's books that never move.
    expect(() => DairyDeductionInstruction.authorise({ ...base, maxPerCycleMinor: 0n , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } })).toThrow(/revoke the arrangement/);
  });

  it('covers every source of its type, or exactly one', () => {
    const blanket = DairyDeductionInstruction.authorise({ ...base , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } });
    expect(blanket.covers('lv-feed', 'any-credit')).toBe(true);
    expect(blanket.covers('lv-loan', 'any-credit')).toBe(false);
    const specific = DairyDeductionInstruction.authorise({ ...base, sourceId: 'credit1' , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } });
    expect(specific.covers('lv-feed', 'credit1')).toBe(true);
    expect(specific.covers('lv-feed', 'credit2')).toBe(false);
  });

  it('is REVOKED, never edited — and a revoked one covers nothing', () => {
    const i = DairyDeductionInstruction.authorise({ ...base , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } });
    i.pullEvents();
    i.revoke(NOW, 'farmer1', { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } });
    expect(i.isActive).toBe(false);
    expect(i.covers('lv-feed', 'credit1')).toBe(false);
    const [e] = i.pullEvents();
    // The member is told it ended too: a revocation nobody can see is a "you can stop this" that cannot be verified.
    expect(e.type).toBe('dairy.deduction_instruction_revoked');
    expect(e.payload).toMatchObject({ userId: 'farmer1', revokedBy: 'farmer1' });
    expect(() => i.revoke(NOW, 'farmer1', { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } })).toThrow(/already ended/);
  });

  it('the SQL writes the arrangement and can only ever revoke it', async () => {
    const tx = { query: jest.fn().mockResolvedValue({ rows: [], rowCount: 1 }) };
    const repo = new DairyDeductionInstructionRepository({ forTenant: () => ({ query: jest.fn() }) } as never);
    const i = DairyDeductionInstruction.authorise({ ...base, maxPerCycleMinor: 20_000n , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } });
    await repo.insert(tx as never, i);
    expect(tx.query.mock.calls[0][0]).toMatch(/INSERT INTO dairy_deduction_instructions/);
    i.revoke(NOW, 'op1', { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } });
    await repo.revoke(tx as never, i);
    const sql = tx.query.mock.calls[1][0];
    expect(sql).toMatch(/SET is_active = false, revoked_at=\$3, revoked_by=\$4/);
    expect(sql).toMatch(/AND is_active/);   // two revocations must not both succeed
    for (const forbidden of ['max_per_cycle_minor=', 'type_id=', 'source_id=', 'authorised_by=']) expect(sql).not.toContain(forbidden);
  });

  it('the revocation FAILS CLOSED', async () => {
    const tx = { query: jest.fn().mockResolvedValue({ rows: [], rowCount: 0 }) };
    const repo = new DairyDeductionInstructionRepository({ forTenant: () => ({ query: jest.fn() }) } as never);
    const i = DairyDeductionInstruction.authorise({ ...base , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } });
    i.revoke(NOW, 'op1', { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } });
    // A caller told "revoked" about a row that did not move would leave the assembler still honouring an arrangement
    // the member thinks is over — money out of a family's bill on the strength of a lie.
    await expect(repo.revoke(tx as never, i)).rejects.toMatchObject({ code: 'DAIRY_DEDUCTION_INSTRUCTION_NOT_FOUND' });
  });

  it('the assembler reads the live arrangements INSIDE the writing transaction', async () => {
    const tx = { query: jest.fn().mockResolvedValue({ rows: [], rowCount: 0 }) };
    const repo = new DairyDeductionInstructionRepository({ forTenant: () => ({ query: jest.fn() }) } as never);
    await repo.activeForMembership(tx as never, 'tA', 'mem1');
    // Off the replica an arrangement revoked ten seconds ago could still be honoured, because this read decides how
    // much of a family's fortnight is withheld.
    expect(tx.query.mock.calls[0][0]).toMatch(/WHERE i\.tenant_id=\$1 AND i\.membership_id=\$2 AND i\.is_active/);
  });
});

/* ----------------------------------------------------------------------------------------------------------- */
describe('THE ASSEMBLER — only what the member arranged', () => {
  const feedType = { id: 'lv-feed', code: 'feed_credit', name: 'Feed', destination: 'member_credit' as const, unsupportedReason: null, sourceType: 'dairy_member_credit' };
  const loanType = { id: 'lv-loan', code: 'loan_emi', name: 'Loan', destination: 'loan' as const, unsupportedReason: null, sourceType: 'loan' };
  const credit = (id: string, value: bigint, issuedOn: string) => DairyMemberCredit.rehydrate({
    id, tenantId: 'tA', membershipId: 'mem1', mccId: null, description: 'feed', valueMinor: value,
    recoveredMinor: 0n, issuedOn, issuedBy: 'op1', status: 'outstanding' });
  const instruction = (over: Partial<{ typeId: string; typeCode: string; sourceId: string | null; maxPerCycleMinor: bigint | null }> = {}) =>
    DairyDeductionInstruction.authorise({
      id: `i-${over.typeId ?? 'lv-feed'}-${over.sourceId ?? 'all'}`, tenantId: 'tA', membershipId: 'mem1',
      typeId: over.typeId ?? 'lv-feed', typeCode: over.typeCode ?? 'feed_credit',
      sourceId: over.sourceId ?? null, maxPerCycleMinor: over.maxPerCycleMinor ?? null,
      authorisedBy: 'farmer1', authorisedAt: NOW, channel: 'app', assistedBy: null, recordedBy: 'farmer1', note: null , notice: { what: { en: 'feed credit' }, how_much: { en: 'INR 200.00' } } });

  function harness(over: { live?: unknown[]; credits?: unknown[]; loans?: unknown[]; pct?: { assemblyPct: number; consentPct: number } } = {}) {
    const instructions = {
      activeForMembership: jest.fn(async () => over.live ?? []),
      assemblyPct: jest.fn(async () => over.pct ?? { assemblyPct: 25, consentPct: 25 }),
    };
    const credits = { listOutstanding: jest.fn(async () => over.credits ?? []) };
    const types = { list: jest.fn(async () => [feedType, loanType]) };
    const memberships = { getById: jest.fn(async () => ({ id: 'mem1', farmerUserId: 'farmer1' })) };
    const loans = { milkDeductibleLoans: jest.fn(async () => over.loans ?? []) };
    const svc = new DairyDeductionAssemblerService(instructions as never, credits as never, types as never, memberships as never, loans as never);
    return { svc, instructions, credits, loans, memberships };
  }
  const tx = { query: jest.fn() } as never;

  it('assembles NOTHING for a member with no arrangement — their whole cheque is theirs', async () => {
    const h = harness({ credits: [credit('credit1', 50_000n, '2026-07-01')] });
    const plan = await h.svc.assemble(tx, 'tA', 'mem1', 400_000n);
    expect(plan.lines).toEqual([]);
    // And it does not even ask for the debts: no arrangement, nothing to plan.
    expect(h.credits.listOutstanding).not.toHaveBeenCalled();
  });

  it('recovers an outstanding credit the member arranged', async () => {
    const h = harness({ live: [instruction()], credits: [credit('credit1', 50_000n, '2026-07-01')] });
    const plan = await h.svc.assemble(tx, 'tA', 'mem1', 400_000n);
    expect(plan.lines).toEqual([expect.objectContaining({ typeCode: 'feed_credit', sourceType: 'dairy_member_credit', sourceId: 'credit1', amountMinor: 50_000n })]);
  });

  it('does NOT recover a debt the member did not arrange, even with a blanket arrangement of another type', async () => {
    const h = harness({ live: [instruction({ typeId: 'lv-loan', typeCode: 'loan_emi' })], credits: [credit('credit1', 50_000n, '2026-07-01')] });
    const plan = await h.svc.assemble(tx, 'tA', 'mem1', 400_000n);
    expect(plan.lines).toEqual([]);
    // A loan arrangement does not authorise recovering feed. This is the whole difference between "authorised" and
    // "automatic", and it is the reason the assembler reads instructions before it reads debts.
  });

  it('a SOURCE-SPECIFIC arrangement wins over the blanket one', async () => {
    // A member who said "₹200 a fortnight on THAT credit" has said something more precise than "recover my credits",
    // and honouring the general rule over the specific one would take more than they agreed to.
    const h = harness({
      live: [instruction(), instruction({ sourceId: 'credit1', maxPerCycleMinor: 20_000n })],
      credits: [credit('credit1', 50_000n, '2026-07-01'), credit('credit2', 30_000n, '2026-07-02')],
    });
    const plan = await h.svc.assemble(tx, 'tA', 'mem1', 400_000n);
    expect(plan.lines).toEqual([
      expect.objectContaining({ sourceId: 'credit1', amountMinor: 20_000n }),
      expect.objectContaining({ sourceId: 'credit2', amountMinor: 30_000n }),
    ]);
  });

  it('does NOT recover a LOAN the member did not arrange, even with an arrangement for another loan', async () => {
    // The loan mirror of the credit case above, and the mutation run's proof that it was needed: falling back to
    // "any loan arrangement will do" would recover loan B on the strength of an instalment agreed for loan A.
    const h = harness({
      live: [instruction({ typeId: 'lv-loan', typeCode: 'loan_emi', sourceId: 'loanA', maxPerCycleMinor: 10_000n })],
      loans: [{ id: 'loanB', outstandingMinor: 200_000n, disbursedAt: '2026-04-01', status: 'active' }],
    });
    expect((await h.svc.assemble(tx, 'tA', 'mem1', 400_000n)).lines).toEqual([]);
  });

  it('LOGS a capped recovery rather than leaving it to be inferred', async () => {
    const spy = jest.spyOn(Logger.prototype, 'log').mockImplementation(() => undefined);
    try {
      const h = harness({ live: [instruction()], credits: [credit('credit1', 5_000_000n, '2026-07-01')] });
      const plan = await h.svc.assemble(tx, 'tA', 'mem1', 400_000n);
      expect(plan.deferred).toHaveLength(1);
      // TENANT-6c-1's ruling about stranded pours, applied: a partial recovery is a real outcome, and an outcome
      // nobody can see is indistinguishable from arithmetic that does not add up.
      expect(spy).toHaveBeenCalledWith(expect.stringContaining('deferred to the next cycle'));
    } finally { spy.mockRestore(); }
  });

  it('reads LOANS through the fintech module\'s public service, by the member\'s user id', async () => {
    const h = harness({
      live: [instruction({ typeId: 'lv-loan', typeCode: 'loan_emi' })],
      loans: [{ id: 'loan1', outstandingMinor: 200_000n, disbursedAt: '2026-04-01', status: 'active' }],
    });
    const plan = await h.svc.assemble(tx, 'tA', 'mem1', 400_000n);
    expect(h.loans.milkDeductibleLoans).toHaveBeenCalledWith(tx, 'tA', 'farmer1');
    expect(plan.lines).toEqual([expect.objectContaining({ typeCode: 'loan_emi', sourceType: 'loan', sourceId: 'loan1', amountMinor: 100_000n })]);
    // Capped at 25% of the gross even though ₹2,000 is outstanding — the automatic path stops at the line.
    expect(plan.capMinor).toBe(100_000n);
    const src = read('../services/dairy-deduction-assembler.service.ts');
    expect(src).toMatch(/from '\.\.\/\.\.\/fintech\/services\/loan\.service'/);
    expect(src).not.toMatch(/fintech\/repositories/);
  });

  it('does not ask the other module anything when no LOAN arrangement exists', async () => {
    const h = harness({ live: [instruction()], credits: [] });
    await h.svc.assemble(tx, 'tA', 'mem1', 400_000n);
    expect(h.loans.milkDeductibleLoans).not.toHaveBeenCalled();
  });

  it('assembles nothing when the tenant has set its cap to zero', async () => {
    const h = harness({ live: [instruction()], credits: [credit('credit1', 50_000n, '2026-07-01')], pct: { assemblyPct: 0, consentPct: 25 } });
    const plan = await h.svc.assemble(tx, 'tA', 'mem1', 400_000n);
    expect(plan.lines).toEqual([]);
    expect(h.credits.listOutstanding).not.toHaveBeenCalled();
  });
});

/* ----------------------------------------------------------------------------------------------------------- */
describe('THE CYCLE — the line that used to be `deductions: []`', () => {
  function harness(opts: { assemblyOn?: boolean; totals?: { totalMinor: bigint; byType: Record<string, string> } } = {}) {
    const cycle = {
      id: 'cyc1', toProps: () => ({ id: 'cyc1', paymentCycle: 'fortnightly', periodStart: '2026-07-01', periodEnd: '2026-07-15' }),
      recordGeneration: jest.fn(), pullEvents: () => [],
    };
    const tx = { query: jest.fn().mockResolvedValue({ rows: [], rowCount: 1 }) };
    const uow = { run: jest.fn(async (_t: string, fn: any) => fn(tx)) };
    const generate = jest.fn(async () => ({ id: 'b1' }));
    const collections = { membershipsToBillForCycle: jest.fn(async () => ['mem1']) };
    const billRepo = {
      billAttemptsByMembership: jest.fn(async () => new Map()),
      cycleTotals: jest.fn(async () => opts.totals ?? { totalMinor: 0n, byType: {} }),
      statusCountsForCycle: jest.fn(async () => ({})),
    };
    const cycles = { getForUpdate: jest.fn(async () => cycle), updateState: jest.fn() };
    const outbox = { write: jest.fn() };
    const flags = { isEnabled: jest.fn(async () => opts.assemblyOn === true) };
    const svc = new DairyBillCycleService(uow as never, outbox as never, metrics as never, { remember: jest.fn() } as never,
      cycles as never, collections as never, { generate } as never, billRepo as never, { getById: jest.fn() } as never,
      billRepo as never, flags as never);
    return { svc, generate, cycle, flags, outbox, billRepo };
  }

  it('asks the assembler ONLY when the flag is on, and once per cycle rather than per member', async () => {
    const h = harness({ assemblyOn: true });
    await h.svc.generateFor('tA', h.cycle as never);
    // 312 identical flag lookups an hour is the shape Law 12 exists to prevent, so it is resolved before the loop.
    expect(h.flags.isEnabled).toHaveBeenCalledTimes(1);
    expect(h.flags.isEnabled).toHaveBeenCalledWith('dairy_deduction_assembly', { tenantId: 'tA' });
    expect((h.generate.mock.calls as any[])[0][5]).toBe(true);
  });

  it('with the flag OFF the cadence still builds bills with NO deductions — where TENANT-6c-4 left it', async () => {
    const h = harness({ assemblyOn: false });
    await h.svc.generateFor('tA', h.cycle as never);
    expect((h.generate.mock.calls as any[])[0][5]).toBe(false);
    expect((h.generate.mock.calls as any[])[0][3]).toMatchObject({ deductions: [] });
  });

  it('reports W169\'s TILE — measured from the lines, and published once', async () => {
    const h = harness({ assemblyOn: true, totals: { totalMinor: 18_430_000n, byType: { feed_credit: '9000000', loan_emi: '9430000' } } });
    const out = await h.svc.generateFor('tA', h.cycle as never);
    expect(out.deductedMinor).toBe('18430000');   // W169: "Deductions this cycle ₹1,84,300"
    const ev = (h.outbox.write.mock.calls as any[]).map((c) => c[1]).find((e) => e.eventType === 'dairy.cycle_deductions_assembled');
    expect(ev.payload).toMatchObject({ totalMinor: '18430000', byType: { feed_credit: '9000000', loan_emi: '9430000' } });
    // No member userId: what a member is told is their BILL (the preview), not that a batch job ran.
    expect(ev.payload.userId).toBeUndefined();
  });

  it('publishes NOTHING when it assembled nothing — an event with no fact in it is noise', async () => {
    const h = harness({ assemblyOn: true });
    const out = await h.svc.generateFor('tA', h.cycle as never);
    expect(out.deductedMinor).toBe('0');
    expect((h.outbox.write.mock.calls as any[]).map((c) => c[1].eventType)).not.toContain('dairy.cycle_deductions_assembled');
  });

  it('an ASSEMBLED line has NO `created_by` — the cadence\'s actor is not a user id', async () => {
    // THE DEFECT THE LIVE SPEC FOUND. `milk_bill_deductions.created_by` is `uuid REFERENCES users(id)` and the
    // cadence's actor is the platform's `'system'` sentinel, so writing it made every assembled line fail with
    // "invalid input syntax for type uuid: system" — the cycle could not create a deduction AT ALL, which is the one
    // thing this wave exists to do. The unit tests mocked the insert and never saw it (fourth time in this programme
    // that a mocked write hid a real column's opinion), so this test asserts the value the row actually gets.
    const src = read('../services/milk-bill.service.ts');
    expect(src).toMatch(/createdBy: isUuid\(actor\.userId\) \? actor\.userId : null/);
    // And a NULL here MEANS "assembled": a line with a `created_by` was typed by a human.
    expect(read(MIGRATION)).toMatch(/a line with no\n-- `created_by` was assembled by the cycle/);
  });

  it('an ASSEMBLED set and a HAND-ENTERED set are never merged', () => {
    // Two different people's decisions about the same fortnight; merging them would double a family's recovery. The
    // guard is in `generate`, and it is a condition rather than a comment.
    expect(read('../services/milk-bill.service.ts')).toMatch(/assembleDeductions && dto\.deductions\.length === 0/);
  });
});

/* ----------------------------------------------------------------------------------------------------------- */
describe('THE READER FOR A STYLE NOTHING HAD EVER SELECTED ON', () => {
  it('joins loans to their product to find `milk_bill_deduction`, and takes only servicing debts', async () => {
    const tx = { query: jest.fn().mockResolvedValue({ rows: [], rowCount: 0 }) };
    const repo = new LoanRepository({ forTenant: () => ({ query: jest.fn() }) } as never);
    await repo.listMilkDeductible(tx as never, 'tA', 'farmer1');
    const sql = tx.query.mock.calls[0][0];
    // `repayment_style` lives on `loan_products` (0011), not on the loan — so this join IS the question "did this
    // family agree that this loan comes out of their milk cheque?".
    expect(sql).toMatch(/JOIN loan_products p/);
    expect(sql).toMatch(/p\.repayment_style = 'milk_bill_deduction'/);
    expect(sql).toMatch(/l\.status IN \('active','overdue'\)/);
    expect(sql).toMatch(/l\.outstanding_minor > 0/);
    expect(sql).toMatch(/WHERE l\.tenant_id=\$1 AND l\.borrower_user_id=\$2/);
    expect(sql).toMatch(/ORDER BY l\.disbursed_at, l\.id/);
  });

  it('and the loan UPDATE now FAILS CLOSED — the family must not pay an instalment they still owe', async () => {
    // Found by asking what TENANT-6c-4's own new caller does if this returns zero rows: the wallet leg has already
    // moved the member's money, so a silently lost update means they paid and still owe, with a ledger entry to
    // prove they paid. Sixth table in this programme to get this guard.
    const tx = { query: jest.fn().mockResolvedValue({ rows: [], rowCount: 0 }) };
    const repo = new LoanRepository({ forTenant: () => ({ query: jest.fn() }) } as never);
    const loan = Loan.rehydrate({ id: 'loan1', applicationId: 'app1', tenantId: 'tA', borrowerUserId: 'farmer1',
      partnerId: 'p1', principalMinor: 200_000n, interestAprBps: 700, disbursedAt: '2026-04-01', maturityDate: null,
      status: 'active', outstandingMinor: 180_000n, nextDueDate: null });
    await expect(repo.update(tx as never, loan)).rejects.toMatchObject({ code: 'LOAN_NOT_FOUND' });
  });
});

/* ----------------------------------------------------------------------------------------------------------- */
describe('WHAT THE MIGRATION AND THE SEED MUST SAY', () => {
  const mig = () => read(MIGRATION);

  it('a NULL source_id is covered by its OWN unique index — 6c-4\'s lesson, applied', () => {
    // `UNIQUE (membership_id, type_id, source_id)` would not constrain the blanket arrangements at all, because
    // Postgres treats NULLs as DISTINCT in a unique index unless declared `NULLS NOT DISTINCT` — the exact defect
    // that left 139 of 311 platform lookup values duplicated.
    expect(mig()).toMatch(/^CREATE UNIQUE INDEX IF NOT EXISTS uq_dairy_ded_instruction_type$/m);
    expect(mig()).toMatch(/^ {2}WHERE source_id IS NULL AND is_active AND deleted_at IS NULL;$/m);
    expect(mig()).toMatch(/^CREATE UNIQUE INDEX IF NOT EXISTS uq_dairy_ded_instruction_source$/m);
    expect(mig()).toMatch(/^ {2}WHERE source_id IS NOT NULL AND is_active AND deleted_at IS NULL;$/m);
  });

  it('keeps the arrangement append-only and revocation-only by GRANT', () => {
    expect(mig()).toMatch(/^REVOKE UPDATE, DELETE ON dairy_deduction_instructions FROM kv_app;$/m);
    expect(mig()).toMatch(/^REVOKE ALL ON dairy_deduction_instructions FROM kv_relay;$/m);
    expect(mig()).toMatch(/^GRANT SELECT, INSERT ON dairy_deduction_instructions TO kv_app;$/m);
    expect(mig()).toMatch(/^GRANT UPDATE \(is_active, revoked_at, revoked_by, updated_at, updated_by\) ON dairy_deduction_instructions TO kv_app;$/m);
  });

  it('cannot let active and revoked disagree, nor an assisted arrangement name nobody', () => {
    expect(mig()).toMatch(/CHECK \(is_active = \(revoked_at IS NULL\) AND \(revoked_at IS NULL\) = \(revoked_by IS NULL\)\)/);
    expect(mig()).toMatch(/CHECK \(\(channel = 'ambassador_assisted'\) = \(assisted_by IS NOT NULL\)\)/);
    expect(mig()).toMatch(/CHECK \(max_per_cycle_minor IS NULL OR max_per_cycle_minor > 0\)/);
  });

  it('seeds the cap as a tenant setting and ships the flag OFF', () => {
    expect(mig()).toMatch(/'dairy\.deduction_assembly_max_pct', 'int', 'tenant', 'money_path', '25'::jsonb/);
    expect(mig()).toMatch(/^   false, 100, 'experiment'\)$/m);
    expect(mig()).toMatch(/'dairy_deduction_assembly'/);
  });

  it('tells the member when a deduction STARTS and when it STOPS, in all three languages', () => {
    const seed = read(SEED_NOTIFS);
    for (const code of ['dairy.deduction_instruction_authorised', 'dairy.deduction_instruction_revoked']) {
      expect(seed).toMatch(new RegExp(`'${code.replace('.', '\\.')}',[^\\n]*'important'[^\\n]*false, false`));
      for (const channel of ['push', 'inapp']) {
        for (const lang of ['en', 'hi', 'gu']) expect(seed).toContain(`('${code}','${channel}','${lang}'`);
      }
    }
    // The revocation copy says the DEBT survives: "this stops the deduction, not the debt". A member told only that
    // the deduction stopped would reasonably believe they no longer owe it.
    expect(seed).toMatch(/stops the deduction, not the debt/);
    // And the arrangement copy names the instalment, because "we will deduct your feed credit" and "we will deduct
    // Rs 200 a fortnight" are different promises.
    expect(seed).toMatch(/\{\{how_much\}\}/);
  });

  it('both notifications are MAPPED to a recipient — a template with no map row sends nothing', () => {
    // ADMIN-6b's finding, six waves running. The seed rows exist above; this is the other half of the pair, and a
    // mutation run removed the map row without a single test noticing.
    const map = read('../../communication/events/notification-event-map.ts');
    for (const code of ['dairy.deduction_instruction_authorised', 'dairy.deduction_instruction_revoked']) {
      expect(map).toMatch(new RegExp(`outboxType: '${code.replace('.', '\\.')}',\\s*eventCode: '${code.replace('.', '\\.')}',\\s*recipientKeys: \\['userId'\\]`));
    }
  });

  it('the member\'s routes carry NO permission and NO flag', () => {
    // Stripped of comments first — the file EXPLAINS that it carries no permission, so a naive search finds the word
    // in the prose. Third time this wave's family of guards has had to learn that (6c-3's commented-out SQL, 6c-4's
    // float guard); a source-level assertion must look at what RUNS.
    const src = read('../controllers/v1/deduction-instructions.controller.ts')
      .replace(/\/\*[\s\S]*?\*\//g, '').split('\n').filter((l) => !l.trim().startsWith('//')).join('\n');
    expect(src).not.toMatch(/@RequirePermissions/);
    expect(src).not.toMatch(/@FeatureFlag\('dairy_deduction_assembly'\)/);
    expect(src).toMatch(/@FeatureFlag\('dairy'\)/);
  });
});

/* ----------------------------------------------------------------------------------------------------------- */
describe('what is deliberately NOT here', () => {
  it('NO PER-TYPE PRIORITY — oldest first, and the alternative is named rather than chosen', () => {
    expect(read('../domain/deduction-plan.ts')).toMatch(/A per-type priority is named/);
    expect(read(MIGRATION)).toMatch(/No per-type priority/);
  });

  it('NO DELEGATED AUTHORITY — an ambassador sits with the member, never instead of them', () => {
    expect(read(MIGRATION)).toMatch(/No delegated authority/);
  });

  it('still no EMI schedule, and still no payout batch — so `paid` is still not a cycle status', () => {
    expect(read(MIGRATION)).toMatch(/Still no EMI schedule/);
    expect(read('../domain/dairy-cycle.ts')).not.toMatch(/'paid'/);
  });
});
