{{- include "krishalaya-common.serviceaccount" . }}
---
{{ include "krishalaya-common.deployment" . }}
---
{{ include "krishalaya-common.service" . }}
---
{{ include "krishalaya-common.hpa" . }}
---
{{ include "krishalaya-common.pdb" . }}

---
{{ include "krishalaya-common.ingress" . }}
