// core/media/s3-presign.service.ts
// ObjectStore — the S3 boundary. Presigning is LOCAL crypto (no network) so it needs no resilience;
// the server-side putObject (used for generated PDFs) is a real network PUT and IS wrapped in
// core/resilience. Config comes from AppConfig.media (bucket/region/creds/endpoint). Fails CLOSED:
// presign refuses if no bucket is configured (a misconfigured deploy can't hand out broken URLs).
import { Injectable } from '@nestjs/common';
import { Readable } from 'node:stream';
import { AppConfig } from '../config/app-config';
import { ResilienceService } from '../resilience/resilience.service';
import { InfraError } from '../../shared/errors/app-error';
import { presignS3Url } from '@krishalaya/storage';

export const OBJECT_STORE = Symbol('OBJECT_STORE');

@Injectable()
export class ObjectStore {
  constructor(private readonly config: AppConfig, private readonly resilience: ResilienceService) {}

  private cfg() {
    const m = this.config.media;
    if (!m.bucket) throw new InfraError('MEDIA_NOT_CONFIGURED', 'object storage bucket is not configured');
    return m;
  }

  presignUpload(key: string, expiresSec?: number): string {
    const m = this.cfg();
    return presignS3Url({ method: 'PUT', region: m.region, bucket: m.bucket, key, accessKeyId: m.accessKeyId, secretAccessKey: m.secretAccessKey, endpoint: m.endpoint, forcePathStyle: m.forcePathStyle, expiresSec: expiresSec ?? m.presignExpirySec });
  }

  presignDownload(key: string, expiresSec?: number): string {
    const m = this.cfg();
    return presignS3Url({ method: 'GET', region: m.region, bucket: m.bucket, key, accessKeyId: m.accessKeyId, secretAccessKey: m.secretAccessKey, endpoint: m.endpoint, forcePathStyle: m.forcePathStyle, expiresSec: expiresSec ?? m.presignExpirySec });
  }

  /** Server-side upload of generated bytes (e.g. statement/invoice PDFs) via a short-lived signed
   *  PUT. Wrapped in resilience (timeout + circuit-breaker); not auto-retried as a money op would be. */
  async putObject(key: string, body: Buffer, contentType: string): Promise<void> {
    const url = this.presignUpload(key, 120);
    await this.resilience.run('s3', async () => {
      const res = await fetch(url, { method: 'PUT', headers: { 'content-type': contentType }, body: body as any });
      if (!res.ok) throw new InfraError('S3_PUT_FAILED', `S3 putObject failed (${res.status})`, { status: res.status });
    });
  }

  /** Server-side download of an object (e.g. for the EXIF-strip job). Resilience-wrapped. */
  async getObject(key: string): Promise<Buffer> {
    const url = this.presignDownload(key, 120);
    return this.resilience.run('s3', async () => {
      const res = await fetch(url, { method: 'GET' });
      if (!res.ok) throw new InfraError('S3_GET_FAILED', `S3 getObject failed (${res.status})`, { status: res.status });
      return Buffer.from(await res.arrayBuffer());
    });
  }

  /**
   * [PC-56 TENANT-6e-2] STREAMING put, for files that must never be held whole in an API pod's memory: the export plane
   * writes a CSV to a temp file while hashing it, then streams that file up as one PUT with its known length. One
   * object, one PUT — S3's single-PUT ceiling is 5 GB, which is a limit the plane names rather than a limit this method
   * hides (`EXPORT_MAX_FILE_BYTES` in the worker). Same presign, same resilience wrap, same failure code as `putObject`.
   *
   * `duplex: 'half'` is what Node's fetch requires to send a streaming request body; the type is cast because the DOM
   * `RequestInit` in the compiler's lib does not declare it while the runtime honours it.
   */
  async putObjectStream(key: string, body: Readable, contentType: string, contentLength: number): Promise<void> {
    const url = this.presignUpload(key, 300);
    await this.resilience.run('s3', async () => {
      const init = { method: 'PUT', headers: { 'content-type': contentType, 'content-length': String(contentLength) }, body: Readable.toWeb(body), duplex: 'half' } as unknown as RequestInit;
      const res = await fetch(url, init);
      if (!res.ok) throw new InfraError('S3_PUT_FAILED', `S3 putObject failed (${res.status})`, { status: res.status });
    });
  }

  /**
   * [PC-56 TENANT-6e-2] STREAMING get: the export download is served THROUGH the API so every fetch can be logged and the
   * digest re-computed over the bytes actually sent (0120's discipline). Buffering a whole export to do that would put
   * a district union's file in the request pod's memory; this hands back the body as a Node stream to pipe.
   */
  async getObjectStream(key: string): Promise<Readable> {
    const url = this.presignDownload(key, 120);
    return this.resilience.run('s3', async () => {
      const res = await fetch(url, { method: 'GET' });
      if (!res.ok || !res.body) throw new InfraError('S3_GET_FAILED', `S3 getObject failed (${res.status})`, { status: res.status });
      return Readable.fromWeb(res.body as unknown as import('node:stream/web').ReadableStream);
    });
  }
}
